version: 2

jobs:
  build:
    docker:
      - image: archlinux/base
      - image: circleci/postgres:12
        environment:
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    steps:
      - run:
          name: Demonstrate that Postgres is available as localhost without password
          command: |
            pacman -Syu --noconfirm postgresql
            psql -h localhost -U postgres -w -c '\l'
